### PR TITLE
Strange bug fixed

### PR DESCRIPTION
**Pull request by tearsofphoenix**
@IDWMaster 
It took me hours to find & fix the bug:
`when generate keypair using the same seed several times, it'll get wrong result after about 3 times`.
 I found we have to uninstantiate the DRBG after generate keypair using seed. So this 
pull request will fix the bug.

### CODE REVIEW

**Comment by IDWMaster** [comment]
Should it also be uninstantiated after every call without the seed as well? There's only a call to uninstantiate in the case where there is a seed specified.

**Comment by tearsofphoenix** [comment]
@IDWMaster  I find if uninstantiated the DRBG without seed, it'll crash. I need to recheck to find out the reason.

**Comment by tearsofphoenix** [comment]
Fixed now. add double check. @IDWMaster

**Comment by tearsofphoenix** [comment]
added auto-build from source now.

**Pull request merged**
