### PR TITLE
add seed support for keypair generation.

### PR DESCRIPTION
**Pull request by tearsofphoenix**
features:
1. If use `seed` parameters, you'll always generate same keypair from `seed`;
2. without `seed`, you'll get different keypair each time

### CODE REVIEW

**Comment by tearsofphoenix** [comment]
Inspired by this repository, I also ported [NTRUMLS](https://github.com/NTRUOpenSourceProject/NTRUMLS) (NTRU Modular Lattice Signature) to [NodeJS version](https://github.com/tearsofphoenix/ntrumls).

**Comment by IDWMaster** [comment]
@tearsofphoenix I've made a few changes to your code. I also tried running your tests, but am having difficulty installing Mocha at the moment due to a networking problem at my location. I've created a new branch called veritasmerge in my repository. Could you take a look at this branch and let me know if you have any questions or comments about my changes before I merge?
Here's a summary of my changes:

* Added call to ntru_crypto_drbg_external_instantiate in case of undefined seed. In the event that the user has previously specified a seed, and wants to switch back to a platform-specific source of entropy, this will allow them to do so.
* Rather than have a single createKey function that takes in a seed value, and one that doesn't; I thought it would be better to have two separate functions. The single function approach seems unintuitive and could easily confuse new users of this library, who may think the seed value is mandatory, or that it is more secure.

**Comment by tearsofphoenix** [comment]
@IDWMaster OK, good work!

**Comment by IDWMaster** [comment]
Pull request has been merged. Closing.

**Pull request merged**
